volumes:
  repo-mount:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/c/Users/ADAM/GitHub/code-graph-mcp
  redis-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /mnt/c/Users/ADAM/.redis-docker/codegraphmcp

services:
  # Redis cache service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  code-graph-sse:
    image: ajacobm/code-graph-mcp:sse
    build:
      context: .
      target: sse
    ports:
      - "10101:8000"
    volumes:
      - ".:/app"  # Mount entire project for development
      - repo-mount:/app/workspace  # Mount workspace
    environment:
      - CODEGRAPHMCP_LOG_LEVEL=DEBUG
      - CODEGRAPHMCP_FILE_WATCHER=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: >
      uv run code-graph-mcp
      --mode sse
      --redis-url redis://redis:6379
      --project-root /app/workspace
      --host 0.0.0.0
      --port 8000
      --verbose
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis monitoring (optional)
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
    profiles:
      - monitoring