version: '3.8'

services:
  # Redis cache service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SSE HTTP Server mode with Redis
  code-graph-sse:
    build:
      context: .
      target: sse
    ports:
      - "8000:8000"
    volumes:
      - "./workspace:/app/workspace:ro"  # Mount your code directory here
    environment:
      - CODE_GRAPH_MCP_LOG_LEVEL=INFO
      - CODE_GRAPH_MCP_FILE_WATCHER=true
      - REDIS_URL=redis://redis:6379
      - CODE_GRAPH_CACHE_TTL=604800
    depends_on:
      - redis
    command: >
      code-graph-mcp
      --mode sse
      --redis-url redis://redis:6379
      --project-root /app/workspace
      --host 0.0.0.0
      --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Stdio mode (for local MCP client connections)
  code-graph-stdio:
    build:
      context: .
      target: stdio
    volumes:
      - "./workspace:/app/workspace:ro"  # Mount your code directory here
    environment:
      - CODE_GRAPH_MCP_LOG_LEVEL=INFO
      - CODE_GRAPH_MCP_FILE_WATCHER=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: >
      code-graph-mcp
      --mode stdio
      --redis-url redis://redis:6379
      --project-root /app/workspace
    restart: unless-stopped
    profiles:
      - stdio  # Only start when explicitly requested

  # Development mode with hot reload
  code-graph-dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"  # Mount entire project for development
      - "./workspace:/app/workspace"  # Mount workspace
    environment:
      - CODE_GRAPH_MCP_LOG_LEVEL=DEBUG
      - CODE_GRAPH_MCP_FILE_WATCHER=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: >
      uv run code-graph-mcp
      --mode sse
      --redis-url redis://redis:6379
      --project-root /app/workspace
      --host 0.0.0.0
      --port 8000
      --verbose
    profiles:
      - dev  # Only start in development profile

  # Redis monitoring (optional)
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
    profiles:
      - monitoring

volumes:
  redis-data: