# Backend-Only Profile
# Use when developing frontend locally with npm/vite
# Backend services run in Docker, frontend runs on host
#
# Usage:
#   docker-compose -f docker-compose.yml -f profiles/backend-only.yml up -d
#   # Then run frontend locally: cd frontend && npm run dev
#
# This disables: frontend, jupyter, memgraph
# Uses GHCR images for quick startup (no build required)

services:
  # Override with GHCR images for faster startup
  codenav-mcp:
    image: ghcr.io/ajacobm/codenav:sse-latest
    build: !reset null
    environment:
      - CODENAV_LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173

  codenav-web:
    image: ghcr.io/ajacobm/codenav:http-latest
    build: !reset null
    environment:
      - CODENAV_LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173

  # Disable services not needed for backend-only mode by putting them in unused profile
  frontend:
    profiles:
      - disabled

  memgraph:
    profiles:
      - disabled

  jupyter:
    profiles:
      - disabled
