# Codespaces Profile
# Optimized for GitHub Codespaces development environment
# - Builds from source for development
# - Includes frontend for Playwright testing with Copilot
# - Uses /workspace mounts (Codespaces convention)
# - Disables heavy services (memgraph, jupyter) to save resources
#
# Usage:
#   docker-compose -f docker-compose.yml -f profiles/codespaces.yml up -d

services:
  redis:
    container_name: codenav-redis-cs
    volumes:
      - /workspace/.redis-data:/data

  # Build from source for development
  codenav-mcp:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: development
    container_name: codenav-sse-cs
    volumes:
      - ..:/app
      - /workspace:/app/workspace
    environment:
      - CODENAV_LOG_LEVEL=DEBUG
      - CODENAV_FILE_WATCHER=true
      - REDIS_URL=redis://redis:6379
    command: >
      uv run codenav
      --mode sse
      --host 0.0.0.0
      --port 8000
      --enable-cache
      --redis-url redis://redis:6379
      --project-root /app/workspace
      --verbose

  codenav-web:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: development
    container_name: codenav-http-cs
    volumes:
      - ..:/app
      - /workspace:/app/workspace
    environment:
      - CODENAV_LOG_LEVEL=DEBUG
      - REDIS_URL=redis://redis:6379
    command: >
      uv run python -m codenav.http_server
      --host 0.0.0.0
      --port 8000
      --redis-url redis://redis:6379
      --project-root /app/workspace

  # Frontend for Playwright testing
  frontend:
    container_name: codenav-frontend-cs
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:10101

  # Disable heavy services in Codespaces by putting them in an unused profile
  memgraph:
    profiles:
      - disabled

  jupyter:
    profiles:
      - disabled
