# GHCR Profile
# Uses pre-built images from GitHub Container Registry
# For testing production builds without building locally
# No notebooks - focused on backend + frontend testing
#
# Usage:
#   docker-compose -f docker-compose.yml -f profiles/ghcr.yml up -d
#
# Requires: docker login ghcr.io

services:
  # Use GHCR images (no build)
  codenav-mcp:
    image: ghcr.io/ajacobm/codenav:sse-latest
    build: !reset null
    container_name: codenav-sse-ghcr
    environment:
      - CODENAV_LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379

  codenav-web:
    image: ghcr.io/ajacobm/codenav:http-latest
    build: !reset null
    container_name: codenav-http-ghcr
    environment:
      - CODENAV_LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379

  frontend:
    image: ghcr.io/ajacobm/codenav-frontend:latest
    build: !reset null
    container_name: codenav-frontend-ghcr
    volumes: !reset []
    environment:
      - VITE_API_URL=http://localhost:10101

  # Disable data science services for GHCR testing
  memgraph:
    profiles:
      - disabled

  jupyter:
    profiles:
      - disabled
