volumes:
  redis-data:
  memgraph-data:

services:
  # Redis cache service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  codenav-mcp:
    image: ajacobm/codenav:sse
    build:
      context: .
      target: sse
    ports:
      - "10101:8000"
    volumes:
      - ${CODENAV_REPO_MOUNT:-/home/adam/GitHub/codenav}:/app/workspace
    environment:
      - CODENAV_LOG_LEVEL=${CODENAV_LOG_LEVEL:-INFO}
      - CODENAV_FILE_WATCHER=${CODENAV_FILE_WATCHER:-true}
      - REDIS_URL=${CODENAV_REDIS_URL:-redis://redis:6379}
    depends_on:
      - redis
    command: >
      uv run codenav
      --mode sse
      --redis-url redis://redis:6379
      --project-root ${CODENAV_PROJECT_ROOT:-/app/workspace/src/codenav}
      --host 0.0.0.0
      --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  codenav-web:
    image: ajacobm/codenav:http
    build:
      context: .
      target: http
    ports:
      - "8000:8000"
    volumes:
      - ${CODENAV_REPO_MOUNT:-/home/adam/GitHub/codenav}:/app/workspace
    environment:
      - REDIS_URL=${CODENAV_REDIS_URL:-redis://redis:6379}
    depends_on:
      - redis
    command: >
      /app/.venv/bin/python -m codenav.http_server
      --project-root /app/workspace/src/codenav
      --host 0.0.0.0
      --port 8000
      --redis-url ${CODENAV_REDIS_URL:-redis://redis:6379}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/app/.venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Redis monitoring (optional)
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  # Memgraph - Graph database for complex Cypher queries
  memgraph:
    image: memgraph/memgraph-platform:latest
    ports:
      - "7687:7687"  # Bolt protocol
      - "3000:3000"  # Lab UI
    volumes:
      - memgraph-data:/var/lib/memgraph
    environment:
      - MEMGRAPH_LOG_LEVEL=WARNING
    command: ["--stream-enabled=true"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "from neo4j import GraphDatabase; driver = GraphDatabase.driver('bolt://localhost:7687'); driver.verify_connectivity(); driver.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Jupyter Data Science Notebook
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - REDIS_URL=redis://redis:6379
      - MEMGRAPH_URL=bolt://memgraph:7687
      - BACKEND_API_URL=http://codenav-web:8000
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - redis
      - memgraph
      - codenav-web
    restart: unless-stopped
    command: start-notebook.sh --ip=0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''

  # Frontend UI (Vue 3 + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - codenav-web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s