services:
  # Redis cache service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  code-graph-sse:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: sse
    ports:
      - "10101:8000"
    volumes:
      - "..:/app"  # Mount current directory as workspace
    environment:
      - CODEGRAPHMCP_LOG_LEVEL=DEBUG
      - CODEGRAPHMCP_FILE_WATCHER=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: >
      python -m pytest tests/test_cdc_sync_validation.py tests/test_query_router_validation.py -v
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "print('ready')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  memgraph:
    image: memgraph/memgraph:latest
    ports:
      - "7687:7687"
    volumes:
      - memgraph-data:/var/lib/memgraph
    command: --flag save-on-exit=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mg_client", "-host", "localhost", "--query", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
  memgraph-data: